### ISSUE TITLE
Is it possible to activate the extension via JavaScript?

### ISSUE THREAD

**Issue by AndreasKarz** [cpulvermacher/time-travel#32]
Is it possible to activate the extension like this:

1. Write the 'timeTravelDate' via Selenium to the SessionStorage
2. Run something like 'window.__timeTravelCheckToggle' 
3. Reload the page via Selenium

**Comment by cpulvermacher** [comment]
What you describe should work for activating/configuring the extension, but getting the content script ([replace_date.ts](https://github.com/cpulvermacher/time-travel/blob/master/src/scripts/replace_date.ts)) into the page might be the main problem. The extension only injects the content script when activated (which is safer and requires less permissions). 

I can think of the following options:
- Ideally, you could control the extension and let it do the work. It looks like this might not be possible with Selenium?
- You could take the **content** of replace_date.ts and execute it in the page via Selenium, then continue with steps 1 & 2. Since the script will be lost by reloading the page, this will only work for new `Date` objects created after the script is executed. 
- If you can modify the frontend code to test, you can add the content of replace_date.ts to it and make sure it's executed before any other initialization.
- It seems to be possible to start chrome with a given extension via --load-extension. You could create a modified version of this extension that has a permanently active content script. (Basically this would require adding replace_date.js to a content_script section in manifest.json, and adding 
```
"host_permissions":[
    "https://*/*",
    "http://*/*"
  ],
```
to enable this on all pages)

**Comment by cpulvermacher** [comment]
Let me close the issue for no, feel free to comment if something worked for you (or didn't).
