### ISSUE TITLE
Time Travel cannot be used. Error: The extensions gallery cannot be scripted.

### ISSUE THREAD

**Issue by toureholder** [cpulvermacher/time-travel#40]
Installed from [the Chrome Web Store](https://chromewebstore.google.com/detail/time-travel/jfdbpgcmmenmelcghpbbkldkcfiejcjg) and I get the error "Time Travel cannot be used. Error: The extensions gallery cannot be scripted."

Chrome Version 129.0.6668.101 (Official Build) (arm64).

![image](https://github.com/user-attachments/assets/6c030ac2-8c84-4416-9a7c-ad640b82c96a)

**Comment by cpulvermacher** [comment]
Hi @toureholder,
this happens if you click the extension icon while the Chrome Web Store is open in the current tab.
Time Travel only affects the current tab. It should work if you switch to the tab where you want to change the time, and then activate the extension again.

Thanks for reporting this though, the error message is not really helpful and I'll check if I can improve it.
